flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- QuickCheck-2.10.0.1
- brick-0.18
- call-stack-0.1.0
- checkers-0.4.7
- data-clist-0.1.2.0
- hspec-2.4.4
- hspec-checkers-0.1.0.2
- hspec-core-2.4.4
- hspec-discover-2.4.4
- hspec-expectations-0.8.2
- protolude-0.1.10
- quickcheck-io-0.2.0
- text-zipper-0.10
- vty-5.17.1
resolver: lts-5.18
